### ISSUE TITLE
Wearing The Armor Produces Large Lag Spikes.

### ISSUE THREAD

**Issue by melancholicMathematics** [tyon2006/AetheriumAshenArmor#7] opened 2022-07-21 02:02 UTC
None of the base Aetherworks items seem to have this same issue, and the crown in the head bauble slot does not seem to cause this either.  I have done some light testing, and it only happens with the armor pieces when they are worn, not when they're in the inventory or in the hand.

**Comment by tyon2006** [comment] 2022-08-12 21:04
Hey can you install optifine and look at the lagometer and see if theres an explanation for where the lag is coming from?

**Comment by melancholicMathematics** [comment] 2022-08-13 20:48
The spikes I was experiencing seem to be coming from gameRenderer, once every two or three seconds or so including the time the game becomes unresponsive which grows each freeze.  I tried a pack of only the required mods and optifine to test, and I only got one small lag spike about one interval after putting the armor on.  I could do some more testing, checking for interactions with various mods aiming for performance that may be changing something, but I am still debating testing my hypothesis of the rendering (or maybe spawning?) of particles from the armor causing issues. The base aetherworks items nor my friends tinker trait implementation of the aetheric effect, nor the crown in head bauble seem to cause this effect, and regular ashen armor works fine in the pack.  might start testing more specific mod interactions later on my own.

**Comment by tyon2006** [comment] 2022-08-16 21:17
This seems really unusual... Would you be willing to join my discord so we could have a higher bandwidth convo? I know a thing or two about troubleshooting weirdo mod issues. 

Link is on the mod page: https://www.curseforge.com/minecraft/mc-mods/aetherium-ashen-armor

**Comment by tyon2006** [comment] 2022-08-22 14:57
Hey @melancholicMathematics just doing a quick follow up. I'll probably close this issue if I don't from you in the near future. We can always re-open it when you're ready to engage.

**Comment by tyon2006** [comment] 2022-10-17 15:49
Closing for now. Cannot reproduce this issue myself, might be a weirdo mod interaction. Let me know if you get new info and need help in the future.

**Closed as completed by tyon2006** 2022-10-17 15:49 UTC
Labels: question, pending confirmation
