### ISSUE TITLE
Attempting to apply inflictor gems on Aetherium cloak causing strange bugs on a server

### ISSUE THREAD

**Issue by Inpaladin** [tyon2006/AetheriumAshenArmor#3] opened 2020-06-23 05:19 UTC
When I try and combine the Aetherium cloak with string and any number of inflictor gems on a regular crafting table it not only does not craft but will delete any items from the workbench if you try and reshuffle them.  It also dupes the string I put in while clicking on blank spaces on any crafting bench as long as I have the Aetherium cloak in the table seemingly at random.

**Comment by tyon2006** [comment] 2020-07-07 12:11
I've seen other mods generate this behavior when mixed with inventory tweaks. 

- Do you have that installed as well? 

- If yes, when you press the sort hotkey (R by default?) does that appear to make any difference? 

- Do the missing items drop on the ground when you leave the crafting table?

- You have embers rekindled installed as well, does this happen to the normal ashen cloak?

-The doubled string - Does the total count in your inventory go up after you close or is the icon just sticking to your mouse?

**Comment by tyon2006** [comment] 2020-07-12 00:13
Alright, I had a look at this and I was unable to reproduce. Recipe worked in both directions and didnt double anything. I even tried it with 1 and more inflictor gems and it always worked. I also tried this with vanilla and a modded crafting table. I'll leave this case open for a bit, but I'll need some more details if I am to help further.

**Comment by Inpaladin** [comment] 2020-07-15 04:23
Hi, sorry I'm late to respond to this, I did have inventory tweaks installed and pressing the sorting hotkey didn't seem to fix the issue.  The string count did increase, leaving the crafting table did not drop items, and I do have embers rekindled and this bug does not occur with the regular cloak.

**Comment by Inpaladin** [comment] 2020-07-15 04:24
I've temporarily shut down the server I was playing on since everyone got kinda bored but if when I play in the future and run into the same bug I'll keep you posted and run more tests.

**Comment by tyon2006** [comment] 2020-08-02 18:17
Okay, I'm gonna close this issue for now but lemme know if it comes back!

**Closed as completed by tyon2006** 2020-08-02 18:17 UTC
Labels: question

**Comment by MajOfMyth** [comment] 2023-10-03 20:00
Hey, I am having similar problems (also on a server). Gems cannot be applied, sometimes deleted, sometimes duplicated. Tried both modded and unmodded crafting tables. Regular ashen cloak can receive gems fine.

**Comment by tyon2006** [comment] 2023-10-04 23:43
Hey can I get a list of the mods that you're using with it? I was never able to reproduce this myself. I won't be able to help without that.
